      
# constants.py

# DFA States
S_START = "START"
S_EVAL_MIN_EXP = "EVAL_MIN_EXP"
S_EVAL_SKILLS = "EVAL_SKILLS"
S_EVAL_PREF_EXP = "EVAL_PREF_EXP"
S_ACCEPT = "FINAL_ACCEPT"
S_REJECT = "FINAL_REJECT"
S_REVIEW = "FINAL_REVIEW"
FINAL_STATES = {S_ACCEPT, S_REJECT, S_REVIEW}

# DFA Input Symbols
SYM_PROCESS = "PROCESS"
SYM_MIN_EXP_MET = "MIN_EXP_MET"
SYM_MIN_EXP_NOT_MET = "MIN_EXP_NOT_MET"
SYM_SKILLS_ALL = "USER_SKILLS_ALL_FOUND"
SYM_SKILLS_PARTIAL = "USER_SKILLS_PARTIAL_FOUND"
SYM_SKILLS_NONE = "USER_SKILLS_NONE_FOUND"
SYM_SKILLS_NA = "USER_SKILLS_NOT_REQUIRED"
SYM_PREF_EXP_MET = "PREF_EXP_MET"
SYM_PREF_EXP_NOT_MET = "PREF_EXP_NOT_MET"
SYM_PREF_EXP_NA = "PREF_EXP_NOT_APPLICABLE"

    